// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Curry = require("bs-platform/lib/js/curry.js");

var dateInDdMmYyyy = (function () {
  const o_date = new Intl.DateTimeFormat();
  const f_date = (m_ca, m_it) => Object({ ...m_ca, [m_it.type]: m_it.value });
  const { day, month, year } = o_date.formatToParts().reduce(f_date, {});
  return day + "/" + month + "/" + year;
});

Curry._1(dateInDdMmYyyy, undefined);

var pathToSomeFile = __dirname + "/someFile.txt";

var pathToResolve = Path.resolve(__dirname, "hello.txt");

console.log(pathToResolve);

var counter = {
  contents: 0
};

function setCounter(step) {
  counter.contents = counter.contents + step | 0;
  
}

setCounter(1);

setCounter(2);

setCounter(3);

setCounter(4);

exports.dateInDdMmYyyy = dateInDdMmYyyy;
exports.pathToSomeFile = pathToSomeFile;
exports.pathToResolve = pathToResolve;
exports.counter = counter;
exports.setCounter = setCounter;
/*  Not a pure module */
