// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SimpleTest = require("./simpleTest.bs.js");

function linkTo(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

var GithubProject__WithoutInterface = {
  linkTo: linkTo
};

var atom = {
  name: "Atom",
  url: "https://atom.io",
  repositories: 255,
  people: 56
};

var atom_link = linkTo(atom);

console.log(atom_link);

function url(t) {
  return t.url;
}

function linkTo$1(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

var GithubProject = {
  url: url,
  linkTo: linkTo$1
};

var node = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 182,
  people: 375
};

var node_link = linkTo$1(node);

var node2 = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 182,
  people: 385
};

var node3 = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 183,
  people: 385
};

SimpleTest.assertEqual("https://nodejs.org", "https://nodejs.org", "[exercise 3] github project url");

function make(name, url, repositories, people) {
  return {
          name: name,
          url: url,
          repositories: repositories,
          people: people
        };
}

function linkTo$2(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

function updatePeople(t, count) {
  return {
          name: t.name,
          url: t.url,
          repositories: t.repositories,
          people: t.people + count | 0
        };
}

function name(t) {
  return t.name;
}

function url$1(t) {
  return t.url;
}

function repositories(t) {
  return t.repositories;
}

function people(t) {
  return t.people;
}

function updateRepositories(t, count) {
  return {
          name: t.name,
          url: t.url,
          repositories: t.repositories + count | 0,
          people: t.people
        };
}

var GithubProject__OpaqueType = {
  make: make,
  linkTo: linkTo$2,
  updatePeople: updatePeople,
  name: name,
  url: url$1,
  repositories: repositories,
  people: people,
  updateRepositories: updateRepositories
};

var rails = {
  name: "Ruby on Rails",
  url: "https://rubyonrails.org",
  repositories: 99,
  people: 66
};

var rails_link = linkTo$2(rails);

console.log("Ruby on Rails");

console.log("https://rubyonrails.org");

console.log(99);

console.log(66);

var rails2 = updateRepositories(rails, 1);

console.log(rails2.repositories);

var Github_WI;

var bookFormat = /* Paperback */1;

var Github_OT;

var Github3;

exports.GithubProject__WithoutInterface = GithubProject__WithoutInterface;
exports.Github_WI = Github_WI;
exports.atom = atom;
exports.atom_link = atom_link;
exports.bookFormat = bookFormat;
exports.GithubProject = GithubProject;
exports.node = node;
exports.node_link = node_link;
exports.node2 = node2;
exports.node3 = node3;
exports.GithubProject__OpaqueType = GithubProject__OpaqueType;
exports.Github_OT = Github_OT;
exports.Github3 = Github3;
exports.rails = rails;
exports.rails_link = rails_link;
exports.rails2 = rails2;
/* atom_link Not a pure module */
